# Generated by Django 3.0.7 on 2020-07-05 20:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_plant_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='last_watered',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
