# Generated by Django 3.0.7 on 2020-07-06 19:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0004_auto_20200706_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='bought',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
