# Generated by Django 3.0.7 on 2020-07-10 18:08

from django.db import migrations
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0005_auto_20200706_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='cropping',
            field=image_cropping.fields.ImageRatioField('image', '300x300', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=True, verbose_name='cropping'),
        ),
    ]
