# Generated by Django 3.0.7 on 2020-07-10 18:59

from django.db import migrations
import image_cropping.fields
import journal.models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0008_auto_20200710_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='image',
            field=image_cropping.fields.ImageCropField(blank=True, default='default.jpg', upload_to=journal.models.user_directory_path),
        ),
    ]
