# Generated by Django 3.0.7 on 2020-07-10 19:15

from django.db import migrations
import image_cropping.fields
import journal.models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0009_auto_20200710_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='cropping',
            field=image_cropping.fields.ImageRatioField('image', '300x300', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='image',
            field=image_cropping.fields.ImageCropField(blank=True, upload_to=journal.models.user_directory_path),
        ),
    ]
