# Generated by Django 3.0.7 on 2020-07-10 19:23

from django.db import migrations, models
import journal.models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0010_auto_20200710_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='image',
            field=models.ImageField(blank=True, default='default.jpg', upload_to=journal.models.user_directory_path),
        ),
    ]
