# Generated by Django 3.0.7 on 2020-07-17 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0012_auto_20200717_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='last_fertilized',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='last_repotted',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='last_treated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
