# Generated by Django 3.0.7 on 2020-06-27 20:57

from django.db import migrations, models
import journal.models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to=journal.models.user_directory_path),
        ),
    ]
